/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface": "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "surface-tint": "#4ae176",
        "primary": "rgb(var(--accent) / <alpha-value>)",
        "primary-fixed": "rgb(var(--accent) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--accent) / <alpha-value>)",
        "primary-container": "#22c55e",
        "on-primary": "#003915",
        "on-primary-container": "#004b1e",
        "on-primary-fixed": "#002109",
        "on-primary-fixed-variant": "#005321",
        "inverse-primary": "#006e2f",
        "secondary": "#4cd7f6",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "secondary-container": "#03b5d3",
        "on-secondary": "#003640",
        "on-secondary-container": "#00424e",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary": "#ffb5ab",
        "tertiary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#ffb4a9",
        "tertiary-container": "#ff8b7c",
        "on-tertiary": "#60130d",
        "on-tertiary-container": "#76231b",
        "on-tertiary-fixed": "#410001",
        "on-tertiary-fixed-variant": "#7f2a21",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "background": "#0b1326",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bccbb9",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "outline": "#869585",
        "outline-variant": "#3d4a3d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px",
        "unit": "4px",
        "section-padding": "80px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-md": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg-mobile": ["var(--font-jetbrains-mono)", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
